### ISSUE TITLE
Pokemon Platinum Wiimmfi

### ISSUE THREAD

**Issue by MagicSheep** [PokeAcer549/wiimmfi-cheatcodes#1]
<game>
<name>Pokemon Platinum</name>
		<gameid>CPUE d074d1b3 3811def6</gameid>
		<date>2009/05/18 10:14</date>
		<cheat>
			<name>Wiimmfi</name>
			<codes>520C42BC EE070F90 E20001C8 0000004E CA02A20D 58CC4B0B D105429C 785C185B 3301701C D1FA4224 00A45E14 3202D005 D3EF1909 881403A1 4778E7F9 EE070F90 E8BD801E 2F2F3A73 D2F2244D 015E0012 0382004D 0009000A 0005000B 00000000 020C42BC E92D401E 020C42C0 FAFCEFC0 D2000000 00000000</codes>
			</cheat>
</game>

**Comment by MagicSheep** [comment]
I think I did it wrong, so here's a pastebin with the xml. http://pastebin.com/HeHX2YQi

**Comment by PokeAcer549** [comment]
Added in commit https://github.com/PokeAcer549/wiimmfi-cheatcodes/commit/e8526c8d0b2f91952d38837960ed47f99f263412
