### ISSUE TITLE
Pokemon hg issue

### ISSUE THREAD

**Issue by cedianoost** [PokeAcer549/wiimmfi-cheatcodes#5]
it works on an EUR version with the USA code, but not with the EUR one.

**Comment by PokeAcer549** [comment]
Pokemon HeartGold has AntiPiracy Checks in that stops it from working.

**Comment by cedianoost** [comment]
nope it's fixed thanks to Apache Thunder ;)

**Comment by cedianoost** [comment]
created a pull request, which fixes up the names. This also explained why certain cheats didn't work

**Comment by PokeAcer549** [comment]
Fixed with PR https://github.com/PokeAcer549/wiimmfi-cheatcodes/pull/6
