### ISSUE TITLE
Mario Kart DS USA HTTP Bypass code- tested and works.

### ISSUE THREAD

**Issue by jaxrogers2** [PokeAcer549/wiimmfi-cheatcodes#8]
```xml
<game>
        <name>Mario Kart DS (USA)</name>
        <gameid>AMCE 59604513</gameid>
        <date>2016/10/12 14:58</date>
        <cheat>
            <name>Bypass HTTPS</name>
            <codes>5200FD08 EE070F90 E20002F8 00000046 CA02A20D 58CC4B0B D105429C 785C185B 3301701C D1FA4224 00A45E14 3202D005 D3EF1909 881403A1 4778E7F9 EE070F90 E8BD801E 2F2F3A73 D2EBD571 0B8000F8 0009000A 00000000 0200FD08 E92D401E 0200FD0C FAFFC179 D2000000 00000000</codes>
            </cheat>
    </game>
```
The full bypass code is 
5200FD08 EE070F90 E20002F8 00000046 CA02A20D 58CC4B0B D105429C 785C185B 3301701C D1FA4224 00A45E14 3202D005 D3EF1909 881403A1 4778E7F9 EE070F90 E8BD801E 2F2F3A73 D2EBD571 0B8000F8 0009000A 00000000 0200FD08 E92D401E 0200FD0C FAFFC179 D2000000 00000000 
I don't know why Github cuts off most of it on the desktop version. It shows all of the code perfectly on mobile though for some reason.

**Comment by PokeAcer549** [comment]
It shows fine in a code block, dont worry 😝 
Added in commit https://github.com/PokeAcer549/wiimmfi-cheatcodes/commit/53b96883506c8f163906fc17764d011dcb0e5367
