### ISSUE TITLE
The legend of zelda Phantom hourglass eur code

### ISSUE THREAD

**Issue by the4anoni** [PokeAcer549/wiimmfi-cheatcodes#9]
<game>
		<name>The Legend of Zelda: Phantom Hourglass</name>
		<gameid>AZEP D505F823</gameid>
		<date>2016/08/20 23:36</date>
		<cheat>
			<name>Bypass HTTPS</name>
			<codes>5200F25C EE070F90 E2000230 00000048 CA02A20D 58CC4B0B D105429C 785C185B 3301701C D1FA4224 00A45E14 3202D005 D3EF1909 881403A1 4778E7F9 EE070F90 E8BD801E 2F2F3A73 D2E86BB1 0009000A 001200A0 0000015D 0200F25C E92D401E 0200F260 FAFFC3F2 D2000000 00000000</codes>
			</cheat>
	</game>

**Comment by PokeAcer549** [comment]
Added in https://github.com/PokeAcer549/wiimmfi-cheatcodes/commit/4016626544a73fd20de39f3d9dfcbee961c54948
